name: Reusable Workflow

on:
  workflow_dispatch:
    inputs:
      test-input:
        description: 'Test input for reusable workflow'
        type: string
        required: true
  repository_dispatch:
    types: [reusable-call]
  push:
    branches:
      - '*'
run-name: ${{ github.actor }} is testing out GitHub Actions  🚀

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: print input
        shell: bash
        run: |
          Write-Output "Input received: ${{ github.event.inputs.test-input }}"

      - name: Run a one-line script
        shell: pwsh
        run: .\code.ps1 
